version: "3.8"

volumes:
  datafiles:

services: 
  www:
    container_name: ehealthwww_sec
    build: ./api_sec
    ports:
      - 5001:5000
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    container_name: ehealthdb_sec
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: eHealth
      MYSQL_ROOT_PASSWORD: estia
    volumes:
      - datafiles:/var/lib/mysql
      - ../db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pestia"]
      timeout: 5s
      retries: 10
    restart: always